"""Explicit effect declarations. No natural-language fallback or automatic support.

The manifest pins every allowed card to the exact reviewed data record. New effects
remain unvalidated until the user runs the prepared fixtures.
"""
import gzip
import hashlib
import json
from pathlib import Path
from engine.cards import SUPPORTED as LEGACY_SUPPORTED, TOKENS as LEGACY_TOKENS, UnsupportedCard

ROOT=Path(__file__).resolve().parents[1]
# Each rule is (target restriction, ordered operations). A spell with no target
# uses 'none'; minion battlecries may resolve without a target when none exists.
RULES = {
 'CORE_SCH_713': ('none', [('opponent_next_turn_cost','SPELL',1)]),
 'CORE_DRG_403': ('none', [('opponent_next_power_cost',2)]),
 'TIME_716': ('none', [('opponent_next_turn_cost','ALL',1)]),
 'TLC_439': ('none', [('area_damage','enemy_minions',2), ('opponent_next_turn_cost','MINION',2)]),
 # Original subset cards now use the shared play lifecycle too.
 'CORE_CS2_189': ('character', [('damage',1)]),
 'CORE_UNG_084': ('character', [('damage',3)]),
 'CORE_EX1_011': ('character', [('heal',2)]),
 'CORE_ULD_191': ('friendly_minion', [('buff',0,2)]),
 'RLK_958': ('friendly_undead', [('buff',2,0)]),
 'CORE_ULD_271': ('none', [('damage_self',3)]),
 'CORE_GIL_622': ('none', [('damage_enemy_heal_own',3,3)]),
 'CORE_EX1_506': ('none', [('summon_right','TOKEN_SCOUT',1)]),
 'RLK_503': ('none', [('gain_corpses',1)]),
 'RLK_708': ('none', [('draw',1)]),
 'CORE_RLK_062': ('none', [('copy_self_right',2)]),
 'CORE_RLK_505': ('none', [('corpse_missiles',5,2)]),

 'CORE_EX1_145': ('none', [('next_discount', 'SPELL', 2, 'turn')]),
 'CORE_DMF_511': ('none', [('next_discount', 'COMBO', 2, 'turn')]),
 'CORE_BT_416': ('none', [('next_discount', 'DEMON', 2, 'persistent')]),
 'CORE_CS2_053': ('none', [('draw_discount', 3)]),
 'CORE_EX1_287': ('none', [('secret', 'CORE_EX1_287')]),
 'CORE_EX1_289': ('none', [('secret', 'CORE_EX1_289')]),
 'CORE_EX1_610': ('none', [('secret', 'CORE_EX1_610')]),
 'CORE_EX1_611': ('none', [('secret', 'CORE_EX1_611')]),
 'CORE_GIL_577': ('none', [('secret', 'CORE_GIL_577')]),
 'CORE_ULD_152': ('none', [('secret', 'CORE_ULD_152')]),

 'CORE_EX1_002': ('enemy_taunt', [('destroy',)]),
 'CORE_EX1_005': ('large_minion', [('destroy',)]),
 'CORE_SW_066': ('minion', [('silence',)]),
 'CORE_SW_072': ('none', [('destroy_enemy_weapon',)]),
 'CATA_203': ('legendary_minion', [('destroy',)]),
 'TLC_255': ('none', [('match_max_mana',)]),
 'CORE_EX1_246': ('minion', [('transform', 'hexfrog')]),
 'CATA_201': ('none', [('bounce_all_enemies',)]),
 'CORE_ULD_280': ('none', []),
 'CORE_EX1_059': ('minion', [('swap_stats',)]),
 'CORE_CS2_188': ('minion', [('temporary_attack_buff', 2)]),
 'CORE_EX1_198': ('minion', [('destroy_gain_health',)]),
 'CORE_ULD_165': ('minion', [('destroy_hurt_hero',)]),
 'CORE_EX1_193': ('none', [('copy_enemy_deck',)]),
 'CORE_CFM_790': ('none', [('pull_enemy_hand',)]),
 'CORE_LOOT_309': ('none', [('armor', 6), ('recruit', 4)]),
 'CORE_TRL_240': ('enemy_minion', [('damage_hero_attack',)]),
 'CORE_BOT_576': ('combo_friendly_minion', [('combo_buff', 4, 0)]),
 'CS3_022': ('weapon_character', [('damage', 2)]),
 'CORE_SW_429': ('none', [('summon', 'SW_429t', 2)]),
 'CORE_DS1_184': ('none', [('discover_deck',)]),
 'CORE_EX1_014': ('none', [('add_opponent', 'EX1_014t', 2)]),
 'EX1_014t': ('minion', [('buff', 1, 1)]),
 'CORE_GVG_061': ('none', [('summon', 'CS2_101t', 3), ('equip', 'CS2_091')]),
 'CORE_EX1_383': ('none', []),
 'CORE_OG_031': ('none', []),
 'CORE_DAL_720': ('none', []),
 'CORE_TRL_900': ('none', [('fill_hand', 'TRL_348t')]),
 'CORE_SCH_512': ('minion', [('damage_resummon', 4)]),
 'CORE_EX1_082': ('none', [('missiles', 'other_characters', 3)]),
 'CORE_BAR_311': ('none', [('missiles', 'enemy_minions', 4)]),
 'CORE_LOOT_373': ('none', [('random_heal', 12)]),
 'CORE_AT_123': ('none', []),
 'CORE_BT_201': ('none', []),
 'CORE_YOD_026': ('none', []),
 'CATA_720': ('none', [('remove_cheap_decks', 2)]),
 'CATA_724': ('none', []),
 'CATA_303': ('minion', [('damage_heal_enemy_if_dead', 5, 5)]),
 'CATA_308': ('none', [('area_damage', 'all_minions', 4)]),
 'CATA_491': ('none', [('descending_aoe', 3)]),
 'CATA_581': ('none', [('board_count_aoe',)]),
 'TLC_601': ('none', [('armor_aoe', 5)]),
 'TLC_606': ('enemy_minion', [('damage_armor_if_dead', 2, 5)]),
 'TLC_633': ('tribal_enemy_minion', [('damage', 6)]),
 'TLC_621': ('none', []),
 'CORE_AT_037': ('none', []),
 'CORE_EX1_154': ('none', []),
 'CORE_EX1_160': ('none', []),
 'CORE_OG_047': ('none', []),
 'CORE_ONY_018': ('none', []),
 'CORE_TSC_650': ('none', []),
 'EDR_233': ('none', []),
 'EDR_257': ('none', []),
 'END_010': ('none', []),
 'EDR_570': ('none', []),

 'RLK_060': ('none', [('raise_corpses', 'RLK_008t', 5)]),
 'CORE_RLK_506': ('none', [('raise_corpses', 'RLK_061t', 6)]),
 'CORE_RLK_118': ('none', [('tomb_guardians',)]),
 'CORE_RLK_063': ('character', [('damage', 5), ('freeze_enemies',), ('summon', 'RLK_063t', 1)]),
 'CORE_TSC_076': ('none', [('summon', 'TSC_076t3', 1), ('summon', 'TSC_076t2', 1), ('summon', 'TSC_076t', 1)]),
 'CORE_DMF_067': ('none', [('draw_both',)]),
 'CORE_KAR_061': ('none', [('draw_tribe', 'BEAST'), ('draw_tribe', 'DRAGON'), ('draw_tribe', 'MURLOC')]),

 'CAP_801': ('minion', [('buff',2,3),('keyword','REBORN'),('keyword','TAUNT')]),
 'CATA_138': ('friendly_minion', [('buff_board_count',)]),
 'CATA_302': ('minion', [('heal_full',),('draw',1)]),
 'CATA_304': ('none', [('damage_self',4)]),
 'CATA_485': ('character', [('damage',2),('damage_random_enemy_minion',1)]),
 'CATA_582': ('none', [('area_damage','all_minions',1),('hero_attack',3)]),
 'CATA_612': ('none', [('freeze_self',)]),
 'EDR_531': ('friendly_minion', [('destroy',),('armor',8)]),
 'END_007': ('character', [('damage',1),('hero_attack',1),('draw',1),('armor',1)]),
 'END_028': ('none', [('destroy_small',4)]),
 'TIME_051': ('none', [('double_self_attack',)]),
 'TIME_061': ('none', [('reverse_deck',)]),
 'TIME_216': ('minion', [('damage_draw_if_alive',5,2)]),
 'TIME_218': ('minion', [('damage',1),('hero_attack',1)]),
 'TIME_601': ('none', [('draw_until',3)]),
 'TIME_720': ('none', [('double_self_health',)]),
 'TLC_620': ('enemy_minion', [('armor',3),('damage_armor',)]),
 'CORE_AT_055': ('character', [('heal',5)]),
 'CORE_AT_064': ('character', [('damage',3),('armor',3)]),
 'CORE_BAR_801': ('character', [('damage',1),('summon','ENGINE_HYENA',1)]),
 'CORE_BOT_222': ('minion', [('damage',4),('damage_own_hero',4)]),
 'CORE_BOT_451': ('none', [('summon','ENGINE_SPARK',2)]),
 'CORE_BRM_013': ('character', [('damage',3),('draw_empty',1)]),
 'CORE_BT_035': ('none', [('hero_attack',2),('draw',1)]),
 'CORE_BT_292': ('minion', [('buff',2,1),('draw',1)]),
 'CORE_BT_480': ('none', [('outcast_draw',1)]),
 'CORE_BT_491': ('none', [('draw',1),('outcast_draw',1)]),
 'CORE_BT_801': ('minion', [('damage',3)]),
 'CORE_CFM_604': ('friendly_character', [('heal',12),('draw',1)]),
 'CORE_CFM_753': ('none', [('hand_buff',1,1)]),
 'CORE_CS1_112': ('none', [('area_damage','enemy_minions',2),('area_heal',2)]),
 'CORE_CS1_130': ('minion', [('damage',3)]),
 'CORE_CS2_004': ('minion', [('buff',0,2),('draw',1)]),
 'CORE_CS2_009': ('minion', [('buff',2,3),('keyword','TAUNT')]),
 'CORE_CS2_023': ('none', [('draw',2)]),
 'CORE_CS2_024': ('character', [('damage',3),('freeze',)]),
 'CORE_CS2_028': ('none', [('area_damage','enemy_minions',2),('freeze_enemies',)]),
 'CORE_CS2_029': ('character', [('damage',6)]),
 'CORE_CS2_032': ('none', [('area_damage','enemy_minions',5)]),
 'CORE_CS2_042': ('character', [('damage',4)]),
 'CORE_CS2_062': ('none', [('area_damage','all_characters',3)]),
 'CORE_CS2_072': ('undamaged_minion', [('damage',2)]),
 'CORE_CS2_074': ('weapon_required', [('weapon_buff',2)]),
 'CORE_CS2_076': ('enemy_minion', [('destroy',)]),
 'CORE_CS2_093': ('none', [('area_damage','enemies',2)]),
 'CORE_CS2_094': ('character', [('damage',3),('draw',1)]),
 'CORE_CS2_108': ('damaged_enemy_minion', [('destroy',)]),
 'CORE_DS1_185': ('character', [('damage',2)]),
 'CORE_EX1_043': ('none', [('self_hand_health',)]),
 'CORE_EX1_058': ('none', [('adjacent_taunt',)]),
 'CORE_EX1_103': ('none', [('other_murloc_health',2)]),
 'CORE_EX1_129': ('none', [('area_damage','enemy_minions',1),('draw',1)]),
 'CORE_EX1_131': ('none', [('combo_summon','EX1_131t',1)]),
 'CORE_EX1_134': ('combo_character', [('combo_damage',3)]),
 'CORE_EX1_169': ('none', [('temporary_mana',1)]),
 'CORE_EX1_197': ('none', [('destroy_large',5)]),
 'CORE_EX1_238': ('character', [('damage',3)]),
 'CORE_EX1_259': ('none', [('area_damage','enemy_minions',3)]),
 'CORE_EX1_278': ('character', [('damage',1),('draw',1)]),
 'CORE_EX1_302': ('minion', [('damage_draw_if_dead',1)]),
 'CORE_EX1_309': ('minion', [('destroy',),('heal_own_hero',3)]),
 'CORE_EX1_310': ('none', [('discard',2)]),
 'CORE_EX1_319': ('none', [('damage_own_hero',3)]),
 'CORE_EX1_362': ('friendly_minion', [('keyword','DIVINE_SHIELD')]),
 'CORE_EX1_391': ('minion', [('damage_draw_if_alive',2)]),
 'CORE_EX1_606': ('none', [('armor',5),('draw',1)]),
 'CORE_EX1_619': ('none', [('health_one',)]),
 'CORE_GIL_623': ('none', [('self_enemy_hand_health',)]),
 'CORE_GVG_059': ('none', [('random_shield_taunt',)]),
 'CORE_ICC_055': ('minion', [('damage',3)]),
 'CORE_ICC_407': ('none', [('remove_enemy_top',)]),
 'CORE_LOOT_013': ('none', [('damage_own_hero',2)]),
 'CORE_NEW1_018': ('none', [('self_weapon_attack',)]),
 'CORE_OG_149': ('none', [('area_damage','other_minions',1)]),
 'CORE_RLK_657': ('none', [('armor',6)]),
 'CORE_RLK_814': ('none', [('shadow_hand_buff',1,1)]),
 'CORE_SW_088': ('character', [('damage',3),('summon','CS2_065',2)]),
 'CORE_SW_108': ('minion', [('damage',2),('add','SW_108t',1)]),
 'CORE_SW_442': ('character', [('damage',4)]),
 'CORE_TRL_111': ('none', [('beast_weapon_durability',1)]),
 'CORE_TRL_307': ('character', [('heal',4),('draw',1)]),
 'CORE_UNG_205': ('enemy_character', [('freeze',)]),
 'CORE_UNG_809': ('none', [('add','UNG_809t1',1)]),
 'CORE_UNG_848': ('none', [('area_damage','other_minions',2)]),
 'CORE_WW_329': ('none', [('taunt_hand_buff',2,2)]),
 'SW_108t': ('minion', [('damage',2)]),
 # Explicitly replace legacy spell resolution so spell damage/lifesteal are correct.
 'TOKEN_COIN': ('none', [('temporary_mana',1)]),
 'RLK_024': ('minion', [('damage',6)]),
 'CORE_EDR_002': ('friendly_undead', [('keyword','POISONOUS')]),
 'RLK_048': ('none', [('board_buff',1,1),('board_keyword','ELUSIVE')]),
 'RLK_707': ('none', [('grave_strength',)]),
 'CORE_RLK_712': ('none', [('blood_tap',)]),
 'CORE_RLK_087': ('none', [('asphyxiate',)]),
 'RLK_709': ('none', [('area_damage','enemies',2),('draw',1)]),
 'DINO_419': ('friendly_beast', [('buff', 2, 2), ('keyword', 'RUSH')]),
 'EDR_476': ('none', [('area_damage', 'enemies', 4), ('area_heal', 4)]),
 'EDR_492': ('none', [('summon', 'EDR_492t', 3)]),
 'EX1_277': ('none', [('missiles', 'enemies', 3)]),
 'JAIL_312': ('none', [('add', 'EX1_277', 3)]),
 'JAIL_441': ('minion', [('damage', 3), ('refresh_power',)]),
 'JAIL_513': ('none', [('self_hand_health',)]),
 'TIME_059': ('none', [('summon', 'TIME_059', 2)]),
 'TIME_605': ('none', [('copy_self_right', 1)]),
 'TIME_710': ('none', [('combo_copy_self', 1)]),
 'TLC_427': ('none', [('add', 'WW_001t', 1)]),
 'TLC_823': ('minion', [('damage', 3), ('next_discount', 'BEAST', 2, 'turn')]),
 'WW_001t': ('character', [('damage', 3)]),
}
# Only listed keyword/stat cards have been reviewed for this engine.
PASSIVE = {
 'CORE_CS2_179', 'CORE_EX1_096', 'CORE_EX1_110', 'CORE_GIL_558', 'CORE_GVG_085', 'CORE_LOOT_137', 'CORE_LOOT_413', 'CORE_NEW1_023', 'CORE_SW_068', 'CORE_ULD_723', 'CS3_038', 'Core_CS2_200', 'RLK_067', 'RLK_511',
 'CATA_133','CATA_305','CATA_467','CATA_475','CORE_BT_187','CORE_BT_351','CORE_CS2_122','CORE_CS2_222','CORE_EX1_007','CORE_EX1_162','CORE_EX1_414','CORE_EX1_507','CORE_EX1_559','CORE_EX1_604','CORE_GIL_534','CORE_GVG_103','CORE_LOOT_044','CORE_NEW1_020','CORE_NEW1_021','CORE_NEW1_022','CORE_NEW1_027','CORE_NX2_028','CORE_OG_044','CORE_OG_218','CORE_UNG_928','CORE_WC_042','CORE_WON_351','EDR_253','EDR_254','JAIL_872','TLC_101','TLC_256','TLC_478','TLC_480','TLC_605',
 'CORE_AV_337','CORE_BAR_310','CORE_ICC_210','CORE_LOOT_368','CORE_ULD_133','CORE_YOP_034','RLK_061',
 'CATA_558','EDR_272','EDR_486','EDR_598','END_031','TIME_045','TIME_053','TIME_056','TLC_248','TIME_603',
 'CORE_AT_052', 'CORE_EX1_250', 'CORE_BT_701', 'CORE_BT_921',
 'CORE_DRG_079', 'CORE_EX1_010', 'CORE_EX1_028', 'CORE_ICC_038', 'CS3_007',
 'CORE_EX1_012', 'CORE_ICC_214', 'CORE_WC_701',
 'CATA_476',
 'CATA_999',
 'CORE_BT_493',
 'CORE_DRG_107',
 'DINO_130',
 'EDR_816',
 'EDR_971',
 'FIR_778',
 'FIR_929',
 'JAIL_007',
 'JAIL_720',
 'TIME_100',
 'TIME_428',
 'TLC_225',
 'TLC_237',
 'TLC_249',
 'TLC_443',
 'TLC_468',
 'TLC_EVENT_402',
}
DEATH_EFFECTS = {
 'JAIL_877t': [('draw',1)],
 'CORE_ULD_280': [('bounce_random_enemy',)],
 'CORE_EX1_383': [('equip', 'EX1_383t')],
 'CORE_OG_031': [('death_summon', 'OG_031a', 1)],
 'CORE_DAL_720': [('bounce_random_friendly', -2)],
 'CORE_YOD_026': [('death_attack_gift',)],
 'CORE_BT_201': [('attack_missiles',)],
 'CORE_AT_123': [('dragon_held_aoe', 3)],
 'CATA_724': [('unlock_mana',)],
 'TLC_621': [('remove_own_top', 3)],

 'CORE_AV_337': [('death_summon', 'AV_337t', 2)],
 'CORE_LOOT_368': [('death_summon', 'CS2_065', 3)],
 'CORE_BAR_310': [('area_heal', 8)],
 'CORE_DMF_067': [('draw_both',)],

 'TIME_603': [('destroy_random_enemy',)],
 'CORE_EX1_012': [('draw',1)],
 'CORE_RLK_657': [('armor',6)],
 'CORE_ICC_214': [('destroy_random_enemy',)],
 'CORE_WC_701': [('area_damage','enemy_minions',1)],
 'CORE_DRG_107': [('add', 'EX1_277', 1)],
 'DINO_130': [('death_summon', 'DINO_130t', 1), ('board_buff', 1, 1)],
 'FIR_778': [('area_damage', 'enemy_minions', 9)],
 'FIR_929': [('draw_school', 'FIRE')],
 'JAIL_007': [('area_damage', 'enemies', 2)],
 'JAIL_720': [('add', 'TOKEN_COIN', 1)],
 'TLC_225': [('death_summon', 'TLC_249', 1)],
 'TLC_237': [('death_summon', 'TLC_237t', 4)],
 'TLC_249': [('missiles', 'enemies', 2)],
 'TLC_443': [('death_summon', 'TLC_443t', 1)],
 'TLC_468': [('death_summon_group', ('TLC_468t1', 'TLC_468t2'))],
 'TLC_EVENT_402': [('destroy_all_minions',)],
}
END_EFFECTS = {'RLK_061': [('raise_corpses', 'RLK_061t', 1)], 'CORE_ICC_210': [('buff_random_other', 1, 1)], 'CORE_ULD_133': [('draw_unspent_mana',)], 'CORE_YOP_034': [('damage_random_enemy_minion', 10)], 'CATA_133': [('buff_others', 1, 1)], 'CATA_305': [('full_health_buff', 0, 3)], 'CATA_475': [('area_damage', 'enemies', 2)], 'TLC_480': [('set_enemies_stats', 1, 1)],
 'CATA_476': [('summon', 'CATA_476t', 1)],
 'CATA_999': [('damage_enemy_hero', 4)],
 'CORE_BT_493': [('missiles', 'enemies', 6)],
 'EDR_816': [('buff_others', 1, 0)],
 'EDR_971': [('heal_both_heroes', 3)],
 'TIME_100': [('hand_buff', 1, 1)],
 'TIME_428': [('buff_others', 0, 1)],
}
# Explicit token rules; never inferred by parsing card text.
NO_CORPSE = {'RLK_008t','RLK_061t'}
TOKEN_IDS = {'JAIL_877t','GIL_577t','AT_037t','CS2_091','EDR_233t2','EX1_014t','EX1_160t','EX1_383t','EX1_tk11','OG_031a','SW_429t','TRL_348t','TSC_650t','TSC_650t4','hexfrog','AV_337t','RLK_008t','RLK_061t','RLK_063t','RLK_118t3','TSC_076t','TSC_076t2','TSC_076t3','CS2_050','CS2_051','CS2_058','NEW1_009','CS2_101t','CS2_082','EX1_131t','CS2_065','SW_108t','UNG_809t1',
 'CATA_476t',
 'DINO_130t',
 'EDR_492t',
 'EX1_277',
 'TLC_237t',
 'TLC_443t',
 'TLC_468t1',
 'TLC_468t2',
 'WW_001t',
}
LOCAL_TOKENS = {
 'ENGINE_HYENA':dict(id='ENGINE_HYENA',name='Hyena',type='MINION',cost=1,attack=1,health=1,races=['BEAST'],mechanics=['RUSH'],collectible=False),
 'ENGINE_SPARK':dict(id='ENGINE_SPARK',name='Spark',type='MINION',cost=1,attack=1,health=1,races=['ELEMENTAL'],mechanics=['RUSH'],collectible=False),
}
PLAYABLE_TOKENS = {'JAIL_877t','GIL_577t','EX1_014t', 'EX1_383t', 'EDR_233t2', 'TSC_650t', 'SW_429t', 'CS2_091', 'EX1_tk11', 'OG_031a', 'hexfrog', 'UNG_809t1', 'TRL_348t', 'TSC_650t4', 'EX1_160t', 'AT_037t',
 'CATA_476t',
 'DINO_130t',
 'EDR_492t',
 'EX1_277',
 'TLC_237t',
 'TLC_443t',
 'TLC_468t1',
 'TLC_468t2',
 'WW_001t',
}
from .locations import LOCATION_RULES

COLLECTIBLE_IDS = (LEGACY_SUPPORTED | PASSIVE | set(RULES) | set(LOCATION_RULES)) - {'TOKEN_COIN','SW_108t','EX1_014t','EX1_277','WW_001t'}


def registry():
    catalog=json.loads((ROOT/'data/standard/cards.json').read_text())
    manifest=json.loads((Path(__file__).parent/'reviewed_cards.json').read_text())
    selected={c['id']:c for c in catalog if c['id'] in COLLECTIBLE_IDS}
    with gzip.open(ROOT/'data/standard/all_cards.json.gz','rt',encoding='utf-8') as source:
        tokens={c['id']:c for c in json.load(source) if c['id'] in TOKEN_IDS}
    reviewed={**selected,**tokens}
    if set(selected)!=COLLECTIBLE_IDS or set(tokens)!=TOKEN_IDS or set(reviewed)!=set(manifest):
        raise UnsupportedCard('Explicit expanded card registry and manifest disagree.')
    for cid,c in reviewed.items():
        if hashlib.sha256(json.dumps(c,sort_keys=True).encode()).hexdigest()!=manifest[cid]:
            raise UnsupportedCard('Card changed; review its implementation: '+cid)
    return {**reviewed,**LEGACY_TOKENS,**LOCAL_TOKENS}

CHOICES = {'CORE_AT_037': [('Living Roots: damage', 'character', [('damage', 2)]), ('Living Roots: Saplings', 'none', [('summon', 'AT_037t', 2)])], 'CORE_EX1_154': [('Wrath: damage', 'minion', [('damage', 3)]), ('Wrath: draw', 'minion', [('damage', 1), ('draw', 1)])], 'CORE_EX1_160': [('Power: buff', 'none', [('board_buff', 1, 1)]), ('Power: Panther', 'none', [('summon', 'EX1_160t', 1)])], 'CORE_OG_047': [('Feral Rage: Attack', 'none', [('hero_attack', 4)]), ('Feral Rage: Armor', 'none', [('armor', 8)])], 'CORE_ONY_018': [('Boomkin: heal', 'none', [('heal_own_hero', 8)]), ('Boomkin: damage', 'character', [('damage', 4)])], 'CORE_TSC_650': [('Flipper Friends: Orca', 'none', [('summon', 'TSC_650t', 1)]), ('Flipper Friends: Otters', 'none', [('summon', 'TSC_650t4', 6)])], 'EDR_233': [('Spirits: Wolves', 'none', [('summon', 'EX1_tk11', 3)]), ('Spirits: Falcons', 'none', [('summon', 'EDR_233t2', 2)])], 'EDR_257': [('Lightmender: Attack and Shield', 'none', [('buff_self', 3, 0), ('keyword_self', 'DIVINE_SHIELD')]), ('Lightmender: Health and Lifesteal', 'none', [('buff_self', 0, 3), ('keyword_self', 'LIFESTEAL')])], 'EDR_570': [('Nightmares: damage', 'none', [('area_damage', 'all_minions', 1)]), ('Nightmares: buff', 'damaged_minion', [('buff', 2, 2)])], 'END_010': [('Timereaver: Attack', 'none', [('set_others_attack', 1)]), ('Timereaver: Health', 'none', [('set_others_health', 1)])]}

AURAS = {'CORE_CS2_122': ('others', 1, 0), 'CORE_CS2_222': ('others', 1, 1), 'CORE_EX1_162': ('adjacent', 1, 0), 'CORE_EX1_507': ('MURLOC', 2, 0), 'CORE_NEW1_027': ('PIRATE', 1, 1)}

CONDITIONAL_ATTACK = {'CORE_EX1_414': ('damaged', 6), 'CORE_OG_218': ('damaged', 3), 'TLC_101': ('damaged', 3), 'CORE_UNG_928': ('enemy_turn', 2), 'TLC_605': ('enemy_turn', 6), 'CORE_WON_351': ('weapon', 2)}

TRIGGERS = {'CORE_EX1_007': ('damaged_self', [('draw', 1)]), 'CORE_EX1_604': ('damaged_minion', [('buff_self', 1, 0)]), 'CORE_BT_351': ('hero_attack', [('buff_self', 1, 0)]), 'CORE_GIL_534': ('hero_attack', [('buff_self', 1, 1)]), 'CORE_NX2_028': ('hero_attack', [('armor', 4), ('draw', 1)]), 'JAIL_872': ('hero_attack', [('draw', 1)]), 'CORE_NEW1_020': ('spell_cast', [('area_damage', 'all_minions', 1)]), 'CORE_EX1_559': ('spell_cast', [('add', 'CORE_CS2_029', 1)]), 'TLC_256': ('spell_cast', [('keyword_self', 'DIVINE_SHIELD')]), 'EDR_254': ('spell_cast', [('buff_spell_cost',)]), 'CORE_WC_042': ('elemental_played', [('buff_self', 1, 0)])}

WEAPON_TRIGGERS = {'EDR_253': [('draw', 1)], 'TLC_478': [('area_damage', 'all_minions', 1)], 'CATA_467': [('buff_random_friendly', 2, 0)]}

START_EFFECTS = {'CORE_GVG_103': ('every', [('buff_self', 1, 0)]), 'CORE_NEW1_021': ('owner', [('destroy_all_minions',)])}
