"""Thirty-card batch: explicit pinned rules and generated dependencies."""
RULES = {'TIME_447': ('character', [('shield_character',), ('hand_buff', 0, 2)]), 'TIME_449': ('none', [('hero_attack', 4), ('when_state', 'no_deck_minions', ('hand_buff', 4, 0))]), 'FIR_777': ('none', [('when_state', 'power_used', ('buff_self', 3, 3))]), 'FIR_908': ('power_used_friendly_minion', [('when_state', 'power_used', ('buff', 1, 2)), ('when_state', 'power_used', ('keyword', 'RUSH'))]), 'MEND_041': ('none', [('when_state', 'no_minion_last_turn', ('refresh_mana', 3))]), 'MEND_043': ('none', [('draw', 1), ('armor', 3), ('when_state', 'no_minion_last_turn', ('draw', 1)), ('when_state', 'no_minion_last_turn', ('armor', 3))]), 'EDR_941': ('minion', [('damage_history', 'deaths', 1)]), 'TLC_517': ('minion', [('damage_history', 'shuffles', 1)]), 'EDR_940': ('none', []), 'FIR_958': ('none', []), 'TIME_019': ('none', [('when_state', 'aura_active', ('area_damage', 'enemies', 3))]), 'TIME_429': ('none', [('equalize_hand_stats',)]), 'TIME_057': ('none', [('reset_hand_costs',)]), 'JAIL_882': ('none', [('copy_deck_spells',)]), 'JAIL_399': ('none', []), 'JAIL_447': ('none', []), 'TIME_017': ('none', []), 'TIME_EVENT_300': ('none', []), 'EDR_263': ('none', []), 'EDR_262': ('minion', [('damage_then_summon_if_dead', 3, 'EDR_850pe')]), 'EDR_490': ('none', []), 'EDR_523': ('friendly_minion', [('bounce_then_summon', 'EDR_523t')]), 'EDR_804': ('friendly_wisp', [('destroy',), ('draw', 3)]), 'TLC_826': ('none', [('insert_fixed', 'UNG_920t2', 10, 'shuffle')]), 'TLC_820': ('none', []), 'MEND_805': ('none', [('copy_deaths_this_turn', 3, 3)]), 'TIME_435': ('enemy_minion_source_health', [('control_target',)]), 'JAIL_035': ('none', [('when_state', 'no_neutral_in_deck', ('summon', 'JAIL_035', 2))]), 'EDR_978': ('none', []), 'JAIL_436': ('none', [('hero_attack', 1), ('armor', 1), ('add', 'JAIL_436t', 1)])}
TOKEN_RULES = {'JAIL_447t': ('minion', [('buff', 4, 4), ('keyword', 'RUSH')]), 'UNG_920t2': ('none', [('draw', 1)]), 'JAIL_436t': ('none', [('hero_attack', 2), ('armor', 2), ('add', 'JAIL_436t2', 1)]), 'JAIL_436t2': ('none', [('hero_attack', 4), ('armor', 4)]), 'TLC_813': ('minion', [('health_by_relation', 2)])}
DEATH_EFFECTS = {'FIR_958': [('death_area_by_turn', 1, 4)], 'JAIL_882': [('filtered_draw', (('type', 'eq', 'SPELL'),), 1)], 'JAIL_399': [('insert_fixed', 'JAIL_399t1', 2, 'bottom')], 'JAIL_447': [('add', 'JAIL_447t', 1)], 'TIME_017': [('death_summon', 'GVG_079', 1)], 'TIME_EVENT_300': [('death_summon', 'NEW1_021', 1)], 'TLC_820': [('add', 'TLC_813', 1)], 'EDR_978': [('insert_fixed', 'EDR_978', 1, 'bottom', 1)]}
CHOICES = {'EDR_263': [('Greatwolf damage', 'none', [('damage_enemy_hero', 4)]), ('Greatwolf wolves', 'none', [('summon', 'EDR_850pe', 2)])], 'EDR_490': [('Night Terrors', 'none', [('summon', 'EDR_490t', 2)]), ('Destroy', 'enemy_minion', [('destroy',)])]}
TOKEN_IDS = {'JAIL_447t', 'JAIL_436t', 'NEW1_021', 'EDR_523t', 'GVG_079', 'EDR_490t', 'TLC_813', 'UNG_920t2', 'JAIL_399t1', 'EDR_850pe', 'JAIL_436t2'}

# Wisp produced by this expansion; metadata needed by named-Wisp effects.
TOKEN_IDS.add('EDR_851t')
